// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhfhqfxosmyxnzuyxpql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoZmhxZnhvc215eG56dXl4cHFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDM0MzUsImV4cCI6MjA1OTE3OTQzNX0.1G9rF3KSV_If8Y_sZD5l6US_JLY8KzkR2TLoBWEDzsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);